In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

##Separate Features and Target
* Here we are considering 'quality' as target
* and rest of the columns as features

In [4]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

##Splitting Data into Train and Test sets

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

##Standardization

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Train on different algorithms


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [11]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [12]:
l_cla.fit(x_train, y_train)
k_cla.fit(x_train, y_train)
d_cla.fit(x_train, y_train)
r_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [16]:
l_c

array([[  1,   0,   0,   0,   0,   0],
       [  0,   1,   6,   5,   0,   0],
       [  1,   0, 104,  29,   1,   0],
       [  0,   1,  48,  78,   8,   0],
       [  0,   0,   3,  23,  10,   0],
       [  0,   0,   0,   1,   0,   0]])

In [17]:
k_c

array([[  0,   1,   0,   0,   0,   0],
       [  0,   0,   8,   4,   0,   0],
       [  0,   0, 102,  32,   1,   0],
       [  0,   0,  45,  79,  11,   0],
       [  0,   0,   8,  18,  10,   0],
       [  0,   0,   0,   1,   0,   0]])

In [18]:
d_c

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  9,  3,  0,  0],
       [ 2,  5, 94, 31,  3,  0],
       [ 0,  5, 36, 81, 11,  2],
       [ 0,  1,  3, 14, 18,  0],
       [ 0,  0,  0,  1,  0,  0]])

In [19]:
r_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   7,   5,   0,   0],
       [  0,   0, 104,  30,   1,   0],
       [  0,   0,  38,  91,   6,   0],
       [  0,   0,   4,  13,  19,   0],
       [  0,   0,   0,   1,   0,   0]])

In [20]:
s_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   7,   5,   0,   0],
       [  0,   0, 106,  29,   0,   0],
       [  0,   0,  56,  79,   0,   0],
       [  0,   0,   3,  33,   0,   0],
       [  0,   0,   0,   1,   0,   0]])

In [21]:
ks_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   7,   5,   0,   0],
       [  0,   0, 104,  30,   1,   0],
       [  0,   0,  46,  83,   6,   0],
       [  0,   0,   2,  22,  12,   0],
       [  0,   0,   0,   1,   0,   0]])

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [24]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.60625
KNN: 0.596875
Decision Tree: 0.603125
Random Forest: 0.66875
Linear SVC: 0.578125
Kernel SVC: 0.621875
